;; Copyright (c) 2026 clogem-press contributors. EPL-2.0 (see LICENSE).
(ns clogem.model
  "The site model (DESIGN.md §5.2 step 3) — one immutable map, and the heart of
  the design.

  The load-bearing idea: **an article's identity is its permalink, and every
  language version shares it** (§6.2). Indexes therefore hold *article ids*, not
  page refs, so dedupe-by-identity is the shape of the model rather than a filter
  a template could forget.

  Identity resolves two ways:

    1. implicitly, by (directory, order, title) — the normal case, nothing
       required of the author;
    2. explicitly, by writing the same `permalink:` in two files — which is what
       lets a variant with a different title, or one that lives elsewhere in the
       tree, join the group anyway.

  v2.1's M2 is visible here: group-level facts that used to be described as
  coming from \"the directory path\" now come from the **primary variant**, with
  a doctor warning when variants disagree. Mechanism 2 makes \"the directory\"
  ambiguous, and naming the primary keeps categories and the sidebar slot
  agreeing with each other by construction."
  (:require [babashka.fs :as fs]
            [clojure.string :as str]
            [clogem.config :as config]
            [clogem.diag :as diag]
            [clogem.frontmatter :as fm]
            [clogem.util :as u]))

;; ---------------------------------------------------------------------------
;; permalinks.edn (mechanism (b): the auxiliary ledger, §7.2)

(def empty-ledger {:version 1 :permalinks {} :tombstones {}})

(defn read-ledger
  [cfg]
  (let [f (config/permalinks-file cfg)]
    (if (fs/exists? f)
      (merge empty-ledger (or (clojure.edn/read-string (slurp (fs/file f))) {}))
      empty-ledger)))

(defn canonical-ledger
  "Sort the ledger's two maps.

  `permalinks.edn` is a **committed** file, so its serialization has to be a
  function of its content and nothing else — otherwise a rewrite that changed
  nothing still lands as a diff, and the reviewer stops reading them. Doing it
  in the writer rather than only in `ledger-from-model` means it holds for every
  caller, including one that round-trips a ledger straight from `read-ledger`
  (whose maps come out of `edn/read-string` in hash order)."
  [ledger]
  (-> ledger
      (assoc :permalinks (into (sorted-map) (:permalinks ledger))
             :tombstones (into (sorted-map) (:tombstones ledger)))))

(defn write-ledger!
  [cfg ledger]
  (let [f      (config/permalinks-file cfg)
        ledger (canonical-ledger ledger)]
    (spit (fs/file f)
          (with-out-str
            (println ";; Generated by clogem-press. Committed deliberately (DESIGN.md §7.2):")
            (println ";;   - whole-site permalink collision detection without re-reading every file")
            (println ";;   - a tombstone ledger so retired URLs can emit redirect stubs (D-15)")
            (println ";;   - identical URLs from a --no-write build")
            (println ";; It is an AUXILIARY. Identity lives in the files' own `permalink:` front matter,")
            (println ";; which is what makes `git mv` URL-safe.")
            (clojure.pprint/pprint ledger)))
    ledger))

;; ---------------------------------------------------------------------------
;; Entries → variants

(defn implicit-key
  "The (directory, order, title) identity of §6.2 mechanism 1.

  `:base-title` — the title parsed from the *filename* — not `:title`, which
  front matter may override for display. §6.2 defines mechanism 1 as \"the same
  base name in the same numbered directory\", and that distinction is
  load-bearing: a translation almost always sets `title:` to the translated
  title, so keying on the display title would give every translated file its own
  identity and its own permalink — silently defeating the entire i18n design."
  [{:keys [dir-key order base-title]}]
  (str dir-key "|" order "|" base-title))

(defn- declared-lang
  "Front matter `lang:` overrides filename inference (§6.1's escape hatch)."
  [cfg entry front-matter]
  (let [declared (:lang front-matter)
        resolved (when declared
                   (or (config/lang-for-suffix cfg (name declared))
                       (do (diag/warn! (:rel-path entry)
                                       (str "front matter lang: " (pr-str declared)
                                            " is not a configured language; ignoring."))
                           nil)))]
    (when (and resolved (:lang entry) (not= resolved (:lang entry)))
      (diag/warn! (:rel-path entry)
                  (str "front matter lang: " (name resolved) " disagrees with the filename suffix "
                       (name (:lang entry)) "; front matter wins.")))
    (or resolved (:lang entry) (config/default-lang cfg))))

(defn load-entries
  "Attach parsed front matter and a resolved language to each scanned entry."
  [cfg entries]
  (into []
        (keep (fn [entry]
                (let [file (fm/read-file (:path entry))]
                  (when (:front-matter file)
                    (let [front (:front-matter file)]
                      (assoc entry
                             :front-matter front
                             :body         (:body file)
                             :raw          (:raw file)
                             :lang         (declared-lang cfg entry front)
                             ;; :base-title is identity (from the filename);
                             ;; :title is display (front matter wins). The
                             ;; scanner may supply :base-title itself when the
                             ;; two differ at scan time — `_posts/` does, because
                             ;; a post's display title drops the date prefix that
                             ;; its identity must keep.
                             :base-title   (or (:base-title entry) (:title entry))
                             :title        (or (:title front) (:title entry))
                             :declared-permalink (some-> (:permalink front) str u/clean-url)))))))
        entries))

;; ---------------------------------------------------------------------------
;; Permalink resolution

(defn- mint-permalink
  [cfg taken]
  (let [prefix (get-in cfg [:content :permalink-prefix])
        len    (get-in cfg [:content :permalink-length])]
    (loop [tries 0]
      (let [candidate (u/clean-url (str prefix (u/random-hex len)))]
        (cond
          (not (taken candidate)) candidate
          (> tries 1000) (throw (ex-info "could not mint a free permalink after 1000 tries"
                                         {:babashka/exit 1}))
          :else (recur (inc tries)))))))

(defn- deterministic-permalink
  "Mechanism (c) (§7.2): the read-only fallback. Derived from the identity key so
  it is reproducible within and across `--no-write` builds. Never persisted and
  never deployed as canonical.

  Checked against `taken` like any other candidate, and re-derived from a salted
  key when it is not free. A hash is not a reservation: six hex characters is a
  16.7-million space, which a few hundred articles make a real birthday risk,
  and the ledger may already own the hash of a *different* article. Salting
  keeps the escape reproducible, which is the only property mechanism (c) has."
  [cfg ikey taken]
  (let [prefix (get-in cfg [:content :permalink-prefix])
        len    (get-in cfg [:content :permalink-length])]
    (loop [n 0]
      (let [candidate (u/clean-url
                       (str prefix (subs (u/sha256-hex (if (zero? n) ikey (str ikey "#" n)))
                                         0 len)))]
        (cond
          (not (taken candidate)) candidate
          (> n 1000) (throw (ex-info "could not derive a free deterministic permalink"
                                     {:babashka/exit 1 :key ikey}))
          :else (recur (inc n)))))))

(defn resolve-permalinks
  "Assign every entry a permalink, and return [entries taken].

  Order of preference, per entry:
    1. its own declared `permalink:`
    2. the single permalink declared by a sibling in its implicit group (§6.2 —
       this is what files a new translation under the existing article without
       the author doing anything)
    3. the ledger's entry for that implicit key (makes --no-write reproducible)
    4. a freshly minted /pages/xxxxxx/ — or, in read-only mode, a deterministic
       hash of the identity key"
  [cfg entries ledger]
  (let [read-only? (not (config/write-front-matter? cfg))
        ledger-by-key (into {} (map (fn [[pl m]] [(:key m) pl])) (:permalinks ledger))
        declared      (into #{} (keep :declared-permalink) entries)
        tombstoned    (set (keys (:tombstones ledger)))
        priority      (config/lang-keys cfg)
        rank          (into {} (map-indexed (fn [i l] [l i])) priority)
        ;; Sorted, so assignment does not depend on the order a hash map
        ;; happened to yield: with two candidates colliding, *which* one keeps
        ;; the base value would otherwise vary between runs, and mechanism (c)
        ;; is worth nothing if it does not reproduce.
        groups        (sort-by key (group-by implicit-key entries))
        ;; Seeded with every permalink anyone already owns. The ledger's were
        ;; missing, so a fresh mint could land on a permalink the ledger assigns
        ;; to a *different* article in the same build. Stale ledger entries stay
        ;; in the set deliberately: a permalink that used to belong to something
        ;; is a URL that was promised, and handing it to unrelated content is
        ;; worse than a 404.
        taken         (atom (into (into declared tombstoned)
                                  (keys (:permalinks ledger))))
        group-permalink
        (fn [ikey members]
          (let [decls (distinct (keep :declared-permalink members))]
            (case (count decls)
              0 (or (get ledger-by-key ikey)
                    (let [p (if read-only?
                              (deterministic-permalink cfg ikey @taken)
                              (mint-permalink cfg @taken))]
                      (swap! taken conj p)
                      p))
              1 (first decls)
              ;; >1: a hard error (§6.2 as amended). Members of one implicit
              ;; group share a directory, a number and a base name; declaring
              ;; different permalinks claims they are two articles in one
              ;; sidebar slot, which is exactly the collision D-3 already makes
              ;; an error, reached by another route. And "identity IS the
              ;; permalink" (§6.2) leaves no third reading.
              ;;
              ;; It used to warn that the highest-priority variant's permalink
              ;; was being used and then hand every declaring member its own,
              ;; so the group split into two articles anyway — the warning
              ;; described a merge that never happened. Merging for real is the
              ;; other option and is worse: front-matter rule 1 forbids
              ;; overwriting a manual value, so the losing file would keep
              ;; saying `/pages/bbb/` on disk while the site served it at
              ;; `/pages/aaa/`, every build, for ever.
              ;;
              ;; Resolution still happens, deterministically, so the rest of
              ;; the doctor report is readable — the same shape config
              ;; validation uses for a bad :langs :default.
              (let [winner (->> members
                                (filter :declared-permalink)
                                (sort-by #(get rank (:lang %) 999))
                                first
                                :declared-permalink)]
                (diag/error!
                 (str/join ", " (sort (map :rel-path members)))
                 (str "language variants of one article declare different permalinks: "
                      (str/join ", " (sort decls)))
                 (str "Using " winner " (the highest-priority variant's) so the rest of this "
                      "report is readable, but the build will not run. Make them agree, "
                      "or move/rename one file so it forms its own article."))
                winner))))]
    [(into []
           (mapcat (fn [[ikey members]]
                     ;; Always the group's permalink, never the member's own
                     ;; declaration. With 0 or 1 distinct declarations the two
                     ;; are the same value; with more, the group is an error and
                     ;; honouring each declaration is what split it.
                     (let [pl (group-permalink ikey members)]
                       (map #(assoc % :permalink pl :implicit-key ikey) members))))
           groups)
     @taken]))

;; ---------------------------------------------------------------------------
;; Identity groups

;; ---------------------------------------------------------------------------
;; Group-level facts that are more than a front-matter lookup

(defn sticky-rank
  "vdoing's `sticky: 1|2|3…` pins an article to the top of the homepage list,
  lowest rank first. `sticky: true` is common in migrated trees and means
  rank 1 (D-P2-4). Anything else — false, nil, a non-numeric string — is not
  sticky. A numeric string is accepted because YAML authors quote things."
  [v]
  (cond
    (true? v)   1
    (number? v) v
    (string? v) (parse-long (str/trim v))
    :else       nil))

(defn page-component
  "The primary variant's `pageComponent`, normalized to {:name String :data map}
  or nil. YAML gives keyword keys; EDN front matter may use strings."
  [pv]
  (when-let [pc (get-in pv [:front-matter :pageComponent])]
    (cond
      (map? pc)    {:name (some-> (or (get pc :name) (get pc "name")) str)
                    :data (let [d (or (get pc :data) (get pc "data"))]
                            (if (map? d)
                              (into {} (map (fn [[k v]] [(keyword (name k)) v])) d)
                              {}))}
      (string? pc) {:name pc :data {}}
      :else        nil)))

(defn catalogue-dir-key
  "The dir-key a Catalogue page's `data.path` names: `01.Guide` → \"/01.Guide\",
  `01.Guide/10.Basics` → \"/01.Guide/10.Basics\" (D-P2-8: the numbered forms,
  exactly as the directories are spelled). nil when there is no path."
  [pc]
  (when-let [path (u/blank->nil (str (get-in pc [:data :path])))]
    (str "/" (-> path (str/replace #"^[/\\\\]+|[/\\\\]+$" "") (str/replace #"\\\\" "/")))))


(defn- pick-primary
  "The primary variant is the first language in :priority that this article
  actually has (§6.3's per-article twist)."
  [cfg variants]
  (let [priority (config/lang-keys cfg)]
    (or (some (fn [l] (when (contains? variants l) l)) priority)
        (first (sort-by name (keys variants))))))

(defn- warn-path-disagreement!
  "v2.1 M2. Variants normally share a directory (mechanism 1 guarantees it), but
  mechanism 2 lets one live elsewhere. When that happens the group still has a
  single answer — the primary variant's — and `doctor` says so, listing every
  path, because a deliberate relocation and a copy-pasted permalink look
  identical from here."
  [permalink variants primary]
  (let [dirs (into {} (map (fn [[l v]] [l (:dir-key v)])) variants)]
    (when (> (count (distinct (vals dirs))) 1)
      (diag/warn!
       permalink
       (str "language variants of this article live in different directories: "
            (str/join ", " (map (fn [[l d]] (str (name l) " → " (u/blank->nil d) "/"))
                                (sort-by (comp name key) dirs))))
       (str "Categories and the sidebar position come from the primary variant ("
            (name primary) "). If that is not what you meant, move the file "
            "beside its siblings; if it is, this warning is the record of the choice.")))))

(defn build-groups
  "Fold entries into identity groups keyed by permalink."
  [cfg entries]
  (into {}
        (map (fn [[permalink members]]
               (let [by-lang (reduce (fn [m e]
                                       (if-let [prev (get m (:lang e))]
                                         (do (diag/error!
                                              (:rel-path e)
                                              (str "two files claim to be the " (name (:lang e))
                                                   " version of " permalink ": "
                                                   (:rel-path prev) " and " (:rel-path e)))
                                             m)
                                         (assoc m (:lang e) e)))
                                     {} (sort-by :rel-path members))
                     primary (pick-primary cfg by-lang)
                     pv      (get by-lang primary)]
                 (warn-path-disagreement! permalink by-lang primary)
                 [permalink
                  {:permalink  permalink
                   :primary    primary
                   :variants   by-lang
                   ;; M2: group facts come from the primary variant, not "the directory"
                   :categories (vec (:categories pv))
                   :dir-key    (:dir-key pv)
                   :order      (:order pv)
                   :kind       (:kind pv)
                   :date       (get-in pv [:front-matter :date])
                   :sticky     (get-in pv [:front-matter :sticky])
                   ;; what the page IS comes from the primary too (§6.2 table)
                   :page-component (page-component pv)
                   :article?   (not (or (get-in pv [:front-matter :pageComponent])
                                        (false? (get-in pv [:front-matter :article]))
                                        (true? (get-in pv [:front-matter :home]))))
                   ;; tags are the one union: a tag added on one version must not
                   ;; hide the article from that tag's index
                   :tags       (vec (distinct (mapcat (fn [[_ v]]
                                                        (let [t (get-in v [:front-matter :tags])]
                                                          (cond (sequential? t) (remove nil? t)
                                                                (some? t) [t]
                                                                :else nil)))
                                                      by-lang)))}])))
        (group-by :permalink entries)))

;; ---------------------------------------------------------------------------
;; URLs (§6.3)

(defn variant-url
  "Where a given variant of an article is served.

    /pages/a1b2c3/          → the primary variant
    /<lang>/pages/a1b2c3/   → any non-primary variant

  With :i18n :prefix-default? true every variant is prefixed and the bare URL
  becomes a redirect stub (D-10 — redirected, not broken)."
  [cfg group lang]
  (let [base   (config/base-path cfg)
        prefix-all? (get-in cfg [:i18n :prefix-default?])
        pl     (:permalink group)]
    (u/clean-url
     (if (and (= lang (:primary group)) (not prefix-all?))
       (str base pl)
       (str base "/" (name lang) pl)))))

(defn identity-url
  "The bare identity URL — where sidebar entries, index rows and wikilinks point
  without needing to know which languages exist."
  [cfg group]
  (u/clean-url (str (config/base-path cfg) (:permalink group))))

(defn best-variant
  "The variant to show a reader of `lang`: that language if the article has it,
  else the primary (§6.8's fallback rule)."
  [group lang]
  (if (contains? (:variants group) lang)
    lang
    (:primary group)))

;; ---------------------------------------------------------------------------
;; Ordering

(defn newest-first
  "The one sort every index shares (§6.8: sort order is language-invariant
  because `date` comes from the primary). Date descending; undated groups
  last; permalink as the final tie-break so the order is total and a rebuild
  cannot reshuffle two same-day articles."
  [groups]
  (sort (fn [a b]
          (let [da (:date a) db (:date b)]
            (cond
              (and da db (not= da db)) (compare db da)
              (and da (nil? db)) -1
              (and db (nil? da)) 1
              :else (compare (:permalink a) (:permalink b)))))
        groups))

;; ---------------------------------------------------------------------------
;; Indexes (§5.2 step 3 — ids, never page refs)

(defn- index-by
  "{key → [permalink …]} over `groups`, keeping `groups`' order inside each
  bucket. `f` yields the keys a group files under — a group with categories
  [\"Guide\" \"Basics\"] is indexed under BOTH (vdoing semantics, D-P2-2)."
  [f groups]
  (reduce (fn [m g]
            (reduce (fn [m k] (update m k (fnil conj []) (:permalink g)))
                    m (distinct (keep #(u/blank->nil (str %)) (f g)))))
          (sorted-map) groups))

(defn archive-key
  "[year month] of a canonical `YYYY-MM-DD …` date string, or nil. Only the
  leading date is read, so `2026-8-1` and `2026-08-01 09:30:00` both file."
  [date]
  (when-let [[_ y m] (re-find #"^\s*(\d{4})-(\d{1,2})" (str date))]
    [(parse-long y) (parse-long m)]))

(defn archives
  "{year {month [permalink …]}}, newest year and month first; groups without a
  parseable date are skipped here and reported by `doctor-checks!`."
  [groups]
  (reduce (fn [m g]
            (if-let [[y mo] (archive-key (:date g))]
              (let [months (get m y (sorted-map-by >))]
                (assoc m y (update months mo (fnil conj []) (:permalink g))))
              m))
          (sorted-map-by >) groups))

;; ---------------------------------------------------------------------------
;; Sidebar tree (D-P2-1)

(defn- dir-key-segments
  [dir-key]
  (vec (remove str/blank? (str/split (str dir-key) #"/"))))

(defn dir-node
  "A directory node, its (order, title) re-derived from the directory NAME via
  `scan/parse-dirname` rather than from any scanner marker — scan_test forbids
  the {:kind :dir} markers from escaping the scanner. (`parse-dirname` is
  reimplemented inline to keep clogem.model free of a dependency on the
  scanner: number before the first dot, title after it.)"
  [dir-key name]
  (let [i (str/index-of name ".")
        order (when i (let [m (re-find #"^\s*([+-]?\d+)" (subs name 0 i))]
                        (when m (parse-long (second m)))))]
    {:kind      :dir
     :name      name
     :dir-key   dir-key
     :order     order
     :numbered? (some? order)
     :title     (if order (subs name (inc i)) name)
     :children  []}))

(defn- node-sort-key
  "vdoing sorts a directory's files and subdirectories TOGETHER by number
  (order-as-array-index); an unnumbered directory (legal at level 1) sorts
  after every numbered sibling."
  [n]
  [(if (:order n) 0 1) (or (:order n) 0) (str (:title n))])

(defn- sort-tree [node]
  (update node :children
          (fn [cs] (->> cs (map #(if (= :dir (:kind %)) (sort-tree %) %))
                        (sort-by node-sort-key) vec))))

(defn- insert-leaf
  "Insert `leaf` under the directory path `segs` (dir names), creating
  directory nodes on the way."
  [node segs leaf key-so-far]
  (if (empty? segs)
    (update node :children conj leaf)
    (let [[seg & more] segs
          key' (str key-so-far "/" seg)
          idx  (some (fn [[i c]] (when (and (= :dir (:kind c)) (= seg (:name c))) i))
                     (map-indexed vector (:children node)))
          child (if idx (nth (:children node) idx) (dir-node key' seg))
          child' (insert-leaf child more leaf key')]
      (if idx
        (assoc-in node [:children idx] child')
        (update node :children conj child')))))

(defn sidebar-tree
  "The whole numbered tree as ONE root node whose children are the top-level
  directories, each a nested {:kind :dir :children […]} of directory nodes and
  {:kind :article :permalink …} leaves.

  One leaf per identity group — never per file — which is exactly M1's point:
  `02.conventions.md` and `02.conventions.zh-Hans.md` are one leaf. A
  mechanism-2 variant living elsewhere creates NO second leaf: the slot is the
  primary's :dir-key (§6.2, v2.1 M2). Non-article pages (catalogue pages,
  `article: false`) ARE leaves — vdoing lists every file; the article
  predicate governs indexes, not the tree (D-P2-1)."
  [groups]
  (sort-tree
   (reduce (fn [root g]
             (insert-leaf root (dir-key-segments (:dir-key g))
                          {:kind :article :permalink (:permalink g)
                           :order (:order g)
                           :title (get-in g [:variants (:primary g) :base-title])}
                          ""))
           {:kind :dir :name "" :dir-key "" :title "" :children []}
           (filter #(= :tree (:kind %)) (vals groups)))))

(defn sidebar
  "{top-dir-name → subtree}, in sidebar order. An article page renders only
  its own top-level directory's tree (D-P2-1), so the map is keyed the way the
  page looks it up."
  [tree]
  (reduce (fn [m n] (assoc m (:name n) n))
          (array-map)
          (:children tree)))

(defn top-dir
  "The top-level directory name of a group's sidebar slot, or nil for posts —
  a post has no structured position (`sidebar: auto`, D-P2-1)."
  [group]
  (when (= :tree (:kind group))
    (first (dir-key-segments (:dir-key group)))))

(defn tree-leaves
  "Every article leaf of a subtree in sidebar order — the order prev/next
  follow for :tree articles (D-P2-7)."
  [node]
  (mapcat (fn [c] (if (= :dir (:kind c)) (tree-leaves c) [c])) (:children node)))

(defn find-dir
  "The directory node at `dir-key` inside `tree`, or nil."
  [tree dir-key]
  (loop [node tree segs (dir-key-segments dir-key)]
    (if (empty? segs)
      node
      (when-let [c (some #(when (and (= :dir (:kind %)) (= (first segs) (:name %))) %)
                         (:children node))]
        (recur c (rest segs))))))

(defn tree-dirs
  "Every directory node of a subtree with its depth (1 = top level)."
  ([node] (tree-dirs node 0))
  ([node depth]
   (mapcat (fn [c] (when (= :dir (:kind c))
                     (cons [c (inc depth)] (tree-dirs c (inc depth)))))
           (:children node))))

;; ---------------------------------------------------------------------------
;; Assembly

(defn build-model
  [cfg entries ledger]
  (let [[entries taken] (resolve-permalinks cfg entries ledger)
        groups          (build-groups cfg entries)
        articles        (newest-first (filter :article? (vals groups)))
        sticky          (->> articles
                             (keep #(when-let [r (sticky-rank (:sticky %))] [r %]))
                             (sort-by first)
                             (mapv (comp :permalink second)))
        tree            (sidebar-tree groups)]
    {:cfg      cfg
     :entries  entries
     :articles groups
     :taken    taken
     ;; D-15. The tombstone register is carried from the ledger that was READ
     ;; into the ledger that will be WRITTEN. Nothing else in the repository
     ;; remembers a permalink that no file declares any more, so dropping it is
     ;; irreversible — and a build rewrites permalinks.edn unconditionally.
     :tombstones (or (:tombstones ledger) {})
     :tree     tree
     :sidebar  (sidebar tree)
     :permalinks (into {} (map (fn [[pl g]] [pl (:dir-key g)])) groups)
     ;; §5.2 step 3: every index holds article IDS, built from identity groups,
     ;; never from entries — dedupe-by-identity is the shape, not a filter.
     ;; All of them are populated only from :article? groups (D-P2-2): a
     ;; catalogue page, an `article: false` page or a `home: true` page never
     ;; enters an index.
     :posts    (mapv :permalink articles)        ; ALL article groups, tree and post kinds (D-P2-4)
     :sticky   sticky                            ; ascending rank; true → 1
     :categories (index-by :categories articles)
     :tags       (index-by :tags articles)
     :archives   (archives articles)
     ;; {dir-key → permalink} for every Catalogue page, so breadcrumbs and nav
     ;; can point at the catalogue that covers a directory (D-P2-7, D-P2-8).
     :catalogue  (into (sorted-map)
                       (keep (fn [g]
                               (let [pc (:page-component g)]
                                 (when (and (= "catalogue" (u/lower (str (:name pc))))
                                            (catalogue-dir-key pc))
                                   [(catalogue-dir-key pc) (:permalink g)])))
                             (vals groups)))}))

;; ---------------------------------------------------------------------------
;; Doctor findings that are not build errors

(defn- variant-disagreements
  "§6.2's group-facts table: `article: false`, `pageComponent` and
  `comment: false` change what a page IS, so variants disagreeing on them is a
  content bug — reported, while the primary's value is what the build uses."
  [group]
  (for [k [:pageComponent :article :comment]
        :let [vals* (into {} (map (fn [[l v]] [l (get-in v [:front-matter k])])) (:variants group))]
        :when (> (count (distinct (vals vals*))) 1)]
    [k vals*]))

(defn doctor-checks!
  "Warnings `doctor` reports over a finished model. They live here rather than
  inside `build-model` so that `analyse` stays exactly as quiet as Phase 1
  left it (build_test pins its single expected warning) and so that they
  fire once per report rather than once per render."
  [{:keys [articles tree catalogue categories tags] :as _model}]
  (doseq [g (vals articles)
          :when (and (:article? g) (nil? (archive-key (:date g))))]
    (diag/warn! (:permalink g)
                (str "no parseable `date:` on the primary variant ("
                     (get-in g [:variants (:primary g) :rel-path]) "); "
                     "the article sorts last and is skipped by /archives/.")))
  (doseq [g (vals articles)
          [k vals*] (variant-disagreements g)]
    (diag/warn! (:permalink g)
                (str "language variants disagree on `" (name k) "`: "
                     (str/join ", " (map (fn [[l v]] (str (name l) " → " (pr-str v)))
                                         (sort-by (comp name key) vals*))))
                (str "These change what a page IS (DESIGN.md §6.2); the primary variant ("
                     (name (:primary g)) ") decides, and the others should agree.")))
  (doseq [[node depth] (tree-dirs tree)
          :when (> depth 3)]
    (diag/warn! (str (subs (:dir-key node) 1) "/")
                (str "directory is " depth " levels deep; vdoing allows numbered "
                     "directories to level 3 and files only at level 4. It renders anyway.")))
  (doseq [[dir-key pl] catalogue
          :when (nil? (find-dir tree dir-key))]
    (diag/warn! pl (str "Catalogue page points at `" (subs dir-key 1)
                        "`, which is not a directory in the content tree.")
                "Use the numbered directory names exactly, e.g. `01.Guide/10.Basics`."))
  (doseq [[what index] [["category" categories] ["tag" tags]]
          [slug ks] (group-by u/slug (keys index))
          :when (> (count ks) 1)]
    (diag/warn! nil (str "these " what " names share the URL slug `" slug "`: "
                         (str/join ", " (map pr-str ks)) "; only one index page can be emitted.")))
  nil)

(defn ledger-from-model
  [model]
  {:version 1
   :permalinks (into (sorted-map)
                     (map (fn [[pl g]]
                            [pl {:key   (get-in g [:variants (:primary g) :implicit-key])
                                 :langs (vec (sort (map name (keys (:variants g)))))
                                 :paths (vec (sort (map :rel-path (vals (:variants g)))))}]))
                     (:articles model))
   ;; Carried through the model from read-ledger (D-15), never re-derived: a
   ;; retired URL is exactly the thing the content tree no longer mentions.
   :tombstones (or (:tombstones model) {})})
