;; Copyright (c) 2026 clogem-press contributors. EPL-2.0 (see LICENSE).
(ns clogem.model
  "The site model (DESIGN.md §5.2 step 3) — one immutable map, and the heart of
  the design.

  The load-bearing idea: **an article's identity is its permalink, and every
  language version shares it** (§6.2). Indexes therefore hold *article ids*, not
  page refs, so dedupe-by-identity is the shape of the model rather than a filter
  a template could forget.

  Identity resolves two ways:

    1. implicitly, by (directory, order, title) — the normal case, nothing
       required of the author;
    2. explicitly, by writing the same `permalink:` in two files — which is what
       lets a variant with a different title, or one that lives elsewhere in the
       tree, join the group anyway.

  v2.1's M2 is visible here: group-level facts that used to be described as
  coming from \"the directory path\" now come from the **primary variant**, with
  a doctor warning when variants disagree. Mechanism 2 makes \"the directory\"
  ambiguous, and naming the primary keeps categories and the sidebar slot
  agreeing with each other by construction."
  (:require [babashka.fs :as fs]
            [clojure.string :as str]
            [clogem.config :as config]
            [clogem.diag :as diag]
            [clogem.frontmatter :as fm]
            [clogem.util :as u]))

;; ---------------------------------------------------------------------------
;; permalinks.edn (mechanism (b): the auxiliary ledger, §7.2)

(def empty-ledger {:version 1 :permalinks {} :tombstones {}})

(defn read-ledger
  [cfg]
  (let [f (config/permalinks-file cfg)]
    (if (fs/exists? f)
      (merge empty-ledger (or (clojure.edn/read-string (slurp (fs/file f))) {}))
      empty-ledger)))

(defn canonical-ledger
  "Sort the ledger's two maps.

  `permalinks.edn` is a **committed** file, so its serialization has to be a
  function of its content and nothing else — otherwise a rewrite that changed
  nothing still lands as a diff, and the reviewer stops reading them. Doing it
  in the writer rather than only in `ledger-from-model` means it holds for every
  caller, including one that round-trips a ledger straight from `read-ledger`
  (whose maps come out of `edn/read-string` in hash order)."
  [ledger]
  (-> ledger
      (assoc :permalinks (into (sorted-map) (:permalinks ledger))
             :tombstones (into (sorted-map) (:tombstones ledger)))))

(defn write-ledger!
  [cfg ledger]
  (let [f      (config/permalinks-file cfg)
        ledger (canonical-ledger ledger)]
    (spit (fs/file f)
          (with-out-str
            (println ";; Generated by clogem-press. Committed deliberately (DESIGN.md §7.2):")
            (println ";;   - whole-site permalink collision detection without re-reading every file")
            (println ";;   - a tombstone ledger so retired URLs can emit redirect stubs (D-15)")
            (println ";;   - identical URLs from a --no-write build")
            (println ";; It is an AUXILIARY. Identity lives in the files' own `permalink:` front matter,")
            (println ";; which is what makes `git mv` URL-safe.")
            (clojure.pprint/pprint ledger)))
    ledger))

;; ---------------------------------------------------------------------------
;; Entries → variants

(defn implicit-key
  "The (directory, order, title) identity of §6.2 mechanism 1.

  `:base-title` — the title parsed from the *filename* — not `:title`, which
  front matter may override for display. §6.2 defines mechanism 1 as \"the same
  base name in the same numbered directory\", and that distinction is
  load-bearing: a translation almost always sets `title:` to the translated
  title, so keying on the display title would give every translated file its own
  identity and its own permalink — silently defeating the entire i18n design."
  [{:keys [dir-key order base-title]}]
  (str dir-key "|" order "|" base-title))

(defn- declared-lang
  "Front matter `lang:` overrides filename inference (§6.1's escape hatch)."
  [cfg entry front-matter]
  (let [declared (:lang front-matter)
        resolved (when declared
                   (or (config/lang-for-suffix cfg (name declared))
                       (do (diag/warn! (:rel-path entry)
                                       (str "front matter lang: " (pr-str declared)
                                            " is not a configured language; ignoring."))
                           nil)))]
    (when (and resolved (:lang entry) (not= resolved (:lang entry)))
      (diag/warn! (:rel-path entry)
                  (str "front matter lang: " (name resolved) " disagrees with the filename suffix "
                       (name (:lang entry)) "; front matter wins.")))
    (or resolved (:lang entry) (config/default-lang cfg))))

(defn load-entries
  "Attach parsed front matter and a resolved language to each scanned entry."
  [cfg entries]
  (into []
        (keep (fn [entry]
                (let [file (fm/read-file (:path entry))]
                  (when (:front-matter file)
                    (let [front (:front-matter file)]
                      (assoc entry
                             :front-matter front
                             :body         (:body file)
                             :raw          (:raw file)
                             :lang         (declared-lang cfg entry front)
                             ;; :base-title is identity (from the filename);
                             ;; :title is display (front matter wins). The
                             ;; scanner may supply :base-title itself when the
                             ;; two differ at scan time — `_posts/` does, because
                             ;; a post's display title drops the date prefix that
                             ;; its identity must keep.
                             :base-title   (or (:base-title entry) (:title entry))
                             :title        (or (:title front) (:title entry))
                             :declared-permalink (some-> (:permalink front) str u/clean-url)))))))
        entries))

;; ---------------------------------------------------------------------------
;; Permalink resolution

(defn- mint-permalink
  [cfg taken]
  (let [prefix (get-in cfg [:content :permalink-prefix])
        len    (get-in cfg [:content :permalink-length])]
    (loop [tries 0]
      (let [candidate (u/clean-url (str prefix (u/random-hex len)))]
        (cond
          (not (taken candidate)) candidate
          (> tries 1000) (throw (ex-info "could not mint a free permalink after 1000 tries"
                                         {:babashka/exit 1}))
          :else (recur (inc tries)))))))

(defn- deterministic-permalink
  "Mechanism (c) (§7.2): the read-only fallback. Derived from the identity key so
  it is reproducible within and across `--no-write` builds. Never persisted and
  never deployed as canonical.

  Checked against `taken` like any other candidate, and re-derived from a salted
  key when it is not free. A hash is not a reservation: six hex characters is a
  16.7-million space, which a few hundred articles make a real birthday risk,
  and the ledger may already own the hash of a *different* article. Salting
  keeps the escape reproducible, which is the only property mechanism (c) has."
  [cfg ikey taken]
  (let [prefix (get-in cfg [:content :permalink-prefix])
        len    (get-in cfg [:content :permalink-length])]
    (loop [n 0]
      (let [candidate (u/clean-url
                       (str prefix (subs (u/sha256-hex (if (zero? n) ikey (str ikey "#" n)))
                                         0 len)))]
        (cond
          (not (taken candidate)) candidate
          (> n 1000) (throw (ex-info "could not derive a free deterministic permalink"
                                     {:babashka/exit 1 :key ikey}))
          :else (recur (inc n)))))))

(defn resolve-permalinks
  "Assign every entry a permalink, and return [entries taken].

  Order of preference, per entry:
    1. its own declared `permalink:`
    2. the single permalink declared by a sibling in its implicit group (§6.2 —
       this is what files a new translation under the existing article without
       the author doing anything)
    3. the ledger's entry for that implicit key (makes --no-write reproducible)
    4. a freshly minted /pages/xxxxxx/ — or, in read-only mode, a deterministic
       hash of the identity key"
  [cfg entries ledger]
  (let [read-only? (not (config/write-front-matter? cfg))
        ledger-by-key (into {} (map (fn [[pl m]] [(:key m) pl])) (:permalinks ledger))
        declared      (into #{} (keep :declared-permalink) entries)
        tombstoned    (set (keys (:tombstones ledger)))
        priority      (config/lang-keys cfg)
        rank          (into {} (map-indexed (fn [i l] [l i])) priority)
        ;; Sorted, so assignment does not depend on the order a hash map
        ;; happened to yield: with two candidates colliding, *which* one keeps
        ;; the base value would otherwise vary between runs, and mechanism (c)
        ;; is worth nothing if it does not reproduce.
        groups        (sort-by key (group-by implicit-key entries))
        ;; Seeded with every permalink anyone already owns. The ledger's were
        ;; missing, so a fresh mint could land on a permalink the ledger assigns
        ;; to a *different* article in the same build. Stale ledger entries stay
        ;; in the set deliberately: a permalink that used to belong to something
        ;; is a URL that was promised, and handing it to unrelated content is
        ;; worse than a 404.
        taken         (atom (into (into declared tombstoned)
                                  (keys (:permalinks ledger))))
        group-permalink
        (fn [ikey members]
          (let [decls (distinct (keep :declared-permalink members))]
            (case (count decls)
              0 (or (get ledger-by-key ikey)
                    (let [p (if read-only?
                              (deterministic-permalink cfg ikey @taken)
                              (mint-permalink cfg @taken))]
                      (swap! taken conj p)
                      p))
              1 (first decls)
              ;; >1: a hard error (§6.2 as amended). Members of one implicit
              ;; group share a directory, a number and a base name; declaring
              ;; different permalinks claims they are two articles in one
              ;; sidebar slot, which is exactly the collision D-3 already makes
              ;; an error, reached by another route. And "identity IS the
              ;; permalink" (§6.2) leaves no third reading.
              ;;
              ;; It used to warn that the highest-priority variant's permalink
              ;; was being used and then hand every declaring member its own,
              ;; so the group split into two articles anyway — the warning
              ;; described a merge that never happened. Merging for real is the
              ;; other option and is worse: front-matter rule 1 forbids
              ;; overwriting a manual value, so the losing file would keep
              ;; saying `/pages/bbb/` on disk while the site served it at
              ;; `/pages/aaa/`, every build, for ever.
              ;;
              ;; Resolution still happens, deterministically, so the rest of
              ;; the doctor report is readable — the same shape config
              ;; validation uses for a bad :langs :default.
              (let [winner (->> members
                                (filter :declared-permalink)
                                (sort-by #(get rank (:lang %) 999))
                                first
                                :declared-permalink)]
                (diag/error!
                 (str/join ", " (sort (map :rel-path members)))
                 (str "language variants of one article declare different permalinks: "
                      (str/join ", " (sort decls)))
                 (str "Using " winner " (the highest-priority variant's) so the rest of this "
                      "report is readable, but the build will not run. Make them agree, "
                      "or move/rename one file so it forms its own article."))
                winner))))]
    [(into []
           (mapcat (fn [[ikey members]]
                     ;; Always the group's permalink, never the member's own
                     ;; declaration. With 0 or 1 distinct declarations the two
                     ;; are the same value; with more, the group is an error and
                     ;; honouring each declaration is what split it.
                     (let [pl (group-permalink ikey members)]
                       (map #(assoc % :permalink pl :implicit-key ikey) members))))
           groups)
     @taken]))

;; ---------------------------------------------------------------------------
;; Identity groups

(defn- pick-primary
  "The primary variant is the first language in :priority that this article
  actually has (§6.3's per-article twist)."
  [cfg variants]
  (let [priority (config/lang-keys cfg)]
    (or (some (fn [l] (when (contains? variants l) l)) priority)
        (first (sort-by name (keys variants))))))

(defn- warn-path-disagreement!
  "v2.1 M2. Variants normally share a directory (mechanism 1 guarantees it), but
  mechanism 2 lets one live elsewhere. When that happens the group still has a
  single answer — the primary variant's — and `doctor` says so, listing every
  path, because a deliberate relocation and a copy-pasted permalink look
  identical from here."
  [permalink variants primary]
  (let [dirs (into {} (map (fn [[l v]] [l (:dir-key v)])) variants)]
    (when (> (count (distinct (vals dirs))) 1)
      (diag/warn!
       permalink
       (str "language variants of this article live in different directories: "
            (str/join ", " (map (fn [[l d]] (str (name l) " → " (u/blank->nil d) "/"))
                                (sort-by (comp name key) dirs))))
       (str "Categories and the sidebar position come from the primary variant ("
            (name primary) "). If that is not what you meant, move the file "
            "beside its siblings; if it is, this warning is the record of the choice.")))))

(defn build-groups
  "Fold entries into identity groups keyed by permalink."
  [cfg entries]
  (into {}
        (map (fn [[permalink members]]
               (let [by-lang (reduce (fn [m e]
                                       (if-let [prev (get m (:lang e))]
                                         (do (diag/error!
                                              (:rel-path e)
                                              (str "two files claim to be the " (name (:lang e))
                                                   " version of " permalink ": "
                                                   (:rel-path prev) " and " (:rel-path e)))
                                             m)
                                         (assoc m (:lang e) e)))
                                     {} (sort-by :rel-path members))
                     primary (pick-primary cfg by-lang)
                     pv      (get by-lang primary)]
                 (warn-path-disagreement! permalink by-lang primary)
                 [permalink
                  {:permalink  permalink
                   :primary    primary
                   :variants   by-lang
                   ;; M2: group facts come from the primary variant, not "the directory"
                   :categories (vec (:categories pv))
                   :dir-key    (:dir-key pv)
                   :order      (:order pv)
                   :kind       (:kind pv)
                   :date       (get-in pv [:front-matter :date])
                   :sticky     (get-in pv [:front-matter :sticky])
                   :article?   (not (or (get-in pv [:front-matter :pageComponent])
                                        (false? (get-in pv [:front-matter :article]))
                                        (true? (get-in pv [:front-matter :home]))))
                   ;; tags are the one union: a tag added on one version must not
                   ;; hide the article from that tag's index
                   :tags       (vec (distinct (mapcat (fn [[_ v]]
                                                        (let [t (get-in v [:front-matter :tags])]
                                                          (cond (sequential? t) (remove nil? t)
                                                                (some? t) [t]
                                                                :else nil)))
                                                      by-lang)))}])))
        (group-by :permalink entries)))

;; ---------------------------------------------------------------------------
;; URLs (§6.3)

(defn variant-url
  "Where a given variant of an article is served.

    /pages/a1b2c3/          → the primary variant
    /<lang>/pages/a1b2c3/   → any non-primary variant

  With :i18n :prefix-default? true every variant is prefixed and the bare URL
  becomes a redirect stub (D-10 — redirected, not broken)."
  [cfg group lang]
  (let [base   (config/base-path cfg)
        prefix-all? (get-in cfg [:i18n :prefix-default?])
        pl     (:permalink group)]
    (u/clean-url
     (if (and (= lang (:primary group)) (not prefix-all?))
       (str base pl)
       (str base "/" (name lang) pl)))))

(defn identity-url
  "The bare identity URL — where sidebar entries, index rows and wikilinks point
  without needing to know which languages exist."
  [cfg group]
  (u/clean-url (str (config/base-path cfg) (:permalink group))))

(defn best-variant
  "The variant to show a reader of `lang`: that language if the article has it,
  else the primary (§6.8's fallback rule)."
  [group lang]
  (if (contains? (:variants group) lang)
    lang
    (:primary group)))

;; ---------------------------------------------------------------------------
;; Sidebar (flat in Phase 1; tree rendering is Phase 2)

(defn sidebar
  "Group articles by their top-level directory, ordered by (order, title).

  One entry per identity group — not per file — which is exactly M1's point:
  `02.conventions.md` and `02.conventions.zh-Hans.md` are one entry, and the
  duplicate-number rule had to be scoped to identity for that to be expressible."
  [cfg groups]
  (let [tree-groups (filter #(= :tree (:kind %)) (vals groups))]
    (->> tree-groups
         (group-by #(first (remove str/blank? (str/split (str (:dir-key %)) #"/"))))
         (into (sorted-map-by
                (fn [a b] (compare [(str a)] [(str b)]))))
         (reduce-kv
          (fn [m top gs]
            (assoc m top (vec (sort-by (juxt #(or (:order %) 9999)
                                             #(str (:dir-key %))
                                             #(str (get-in % [:variants (:primary %) :title])))
                                       gs))))
          {}))))

;; ---------------------------------------------------------------------------
;; Assembly

(defn build-model
  [cfg entries ledger]
  (let [[entries taken] (resolve-permalinks cfg entries ledger)
        groups          (build-groups cfg entries)]
    {:cfg      cfg
     :entries  entries
     :articles groups
     :taken    taken
     ;; D-15. The tombstone register is carried from the ledger that was READ
     ;; into the ledger that will be WRITTEN. Nothing else in the repository
     ;; remembers a permalink that no file declares any more, so dropping it is
     ;; irreversible — and a build rewrites permalinks.edn unconditionally.
     :tombstones (or (:tombstones ledger) {})
     :sidebar  (sidebar cfg groups)
     :permalinks (into {} (map (fn [[pl g]] [pl (:dir-key g)])) groups)
     :posts    (->> (vals groups)
                    (filter #(and (:article? %) (= :post (:kind %))))
                    (sort-by :date)
                    reverse
                    (mapv :permalink))}))

(defn ledger-from-model
  [model]
  {:version 1
   :permalinks (into (sorted-map)
                     (map (fn [[pl g]]
                            [pl {:key   (get-in g [:variants (:primary g) :implicit-key])
                                 :langs (vec (sort (map name (keys (:variants g)))))
                                 :paths (vec (sort (map :rel-path (vals (:variants g)))))}]))
                     (:articles model))
   ;; Carried through the model from read-ledger (D-15), never re-derived: a
   ;; retired URL is exactly the thing the content tree no longer mentions.
   :tombstones (or (:tombstones model) {})})
